### ISSUE TITLE
bin/startup issue

### ISSUE THREAD

**Issue by dhruvmgit** [forem/selfhost#46]
Hi ,

After i ran the bin/startup i am getting below the error in the browser. Any one let me know the issue.

![image](https://user-images.githubusercontent.com/90322645/132502858-ff0b51a8-c696-4093-8fe5-6ee70edb480d.png)

**Comment by andygeorge** [comment]
@dhruvmgit Thank you for your interest in Forem! This repository is for Forem Selfhost only. The `bin/setup` script is for [running Forem as a developer](https://developers.forem.com/), which is independent from Selfhost.

For support on your issue here (and general Forem app questions), you may make a post on https://forem.dev.
